### ISSUE TITLE
vue router的導向問題

### ISSUE THREAD

**Issue by Jayyyu1w** [Jayyyu1w/NTOU-course-guide-system#2]
目前課程詳細頁面無法導向其他的頁面
錯誤代碼為
```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <RouterView> 
  at <HomeView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:40

runtime-dom.esm-bundler.js:35 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (runtime-dom.esm-bundler.js:35:30)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5713:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:36)
    at flushJobs (runtime-core.esm-bundler.js:390:17)
```

**Comment by Jayyyu1w** [comment]
在RouterView內使用:key="$route.fullPath"來強制刷新頁面便可解決
```
<RouterView :key="$route.fullPath" />
```

**Comment by Jayyyu1w** [comment]
在RouterView內使用:key="$route.fullPath"來強制刷新頁面便可解決
```
<RouterView :key="$route.fullPath" />
```
